name: Build and Publish NuGet Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Utilise un runner Windows

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore Dtwo.Plugins.MultiAccount.csproj

    - name: Build project
      run: dotnet build Dtwo.Plugins.MultiAccount.csproj --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack Dtwo.Plugins.MultiAccount.csproj --configuration Release --no-restore --output ./nupkg

    - name: Publish to GitHub Packages
      run: dotnet nuget push "./nupkg/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
